# Generated by Django 2.2.1 on 2019-12-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVAPP', '0002_auto_20191216_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='requests',
            field=models.ManyToManyField(blank=True, null=True, to='REZERVAPP.Request'),
        ),
    ]
