# Generated by Django 2.2.1 on 2019-12-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVAPP', '0006_auto_20191220_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
