# Generated by Django 2.2.1 on 2019-12-20 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVAPP', '0007_remove_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='best',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='best',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REZERVAPP.profile'),
        ),
    ]
