# Generated by Django 2.2.1 on 2019-12-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVAPP', '0010_auto_20191220_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='best',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='best',
            name='profile_id',
            field=models.ManyToManyField(to='REZERVAPP.profile'),
        ),
        migrations.RemoveField(
            model_name='best',
            name='resturant_id',
        ),
        migrations.AddField(
            model_name='best',
            name='resturant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REZERVAPP.Resturant'),
        ),
    ]
