# Generated by Django 2.2.1 on 2019-12-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVAPP', '0011_auto_20191221_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='best',
            old_name='profile_id',
            new_name='profile_name',
        ),
        migrations.RenameField(
            model_name='best',
            old_name='resturant_id',
            new_name='resturant_name',
        ),
    ]
