# Generated by Django 2.2.1 on 2019-12-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVAPP', '0012_auto_20191221_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resturant',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.AutoField(max_length=264, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resturant',
            name='name',
            field=models.AutoField(max_length=264, primary_key=True, serialize=False, unique=True),
        ),
    ]
