# Generated by Django 2.2.1 on 2019-11-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='best',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('rest_admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_people', models.IntegerField(default='', editable=False)),
                ('RequestTypes', models.CharField(choices=[('AC', 'Accepted'), ('REJ', 'rejected'), ('CANC', 'canceled'), ('PEND', 'pending')], default='AC', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='ResturantAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic', models.IntegerField(default='', editable=False)),
                ('pending_requests', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, to='REZERVAPP.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('traffic', models.IntegerField()),
                ('rate', models.FloatField(default='', editable=False)),
                ('location', models.CharField(max_length=264, unique=True)),
                ('Requests', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, to='REZERVAPP.Request')),
                ('favourite', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, to='REZERVAPP.best')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('picture', models.CharField(max_length=264, unique=True)),
                ('Email', models.CharField(max_length=264, unique=True)),
                ('requests', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, to='REZERVAPP.Request')),
            ],
        ),
        migrations.AddField(
            model_name='best',
            name='profile_id',
            field=models.ManyToManyField(to='REZERVAPP.profile'),
        ),
        migrations.AddField(
            model_name='best',
            name='resturant_id',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, to='REZERVAPP.Resturant'),
        ),
    ]
