# Generated by Django 2.2.1 on 2019-11-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturantadmin',
            name='pending_requests',
        ),
    ]
