# Generated by Django 2.2.1 on 2019-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='best',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264, unique=True)),
                ('picture', models.CharField(max_length=264, unique=True)),
                ('Email', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('rest_admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=264, null=True)),
                ('no_of_people', models.CharField(max_length=264, null=True)),
                ('date', models.CharField(max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=True)),
                ('canceled', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('traffic', models.IntegerField()),
                ('rate', models.CharField(blank=True, max_length=264, null=True)),
                ('favourite', models.CharField(blank=True, max_length=264, null=True)),
                ('Requests', models.CharField(blank=True, max_length=264, null=True)),
                ('location', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResturantAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.DeleteModel(
            name='document',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='coursre',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.DeleteModel(
            name='video',
        ),
        migrations.DeleteModel(
            name='answers',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.DeleteModel(
            name='coursres',
        ),
        migrations.DeleteModel(
            name='posts',
        ),
        migrations.DeleteModel(
            name='questions',
        ),
        migrations.DeleteModel(
            name='quiz',
        ),
        migrations.AddField(
            model_name='best',
            name='profile_id',
            field=models.ManyToManyField(to='REZERVAPP.profile'),
        ),
        migrations.AddField(
            model_name='best',
            name='resturant_id',
            field=models.ManyToManyField(to='REZERVAPP.Resturant'),
        ),
    ]
