# Generated by Django 2.2.1 on 2019-12-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best',
            name='resturant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REZERVAPP.Resturant'),
        ),
        migrations.AlterField(
            model_name='resturantadmin',
            name='resturantid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REZERVAPP.Resturant'),
        ),
    ]
