# Generated by Django 2.2.1 on 2019-11-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVAPP', '0002_remove_resturantadmin_pending_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='requests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REZERVAPP.Request'),
        ),
    ]
