# Generated by Django 2.2.1 on 2019-11-30 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REZERVAPP', '0003_auto_20191130_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best',
            name='resturant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REZERVAPP.Resturant'),
        ),
        migrations.AlterField(
            model_name='resturant',
            name='Requests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REZERVAPP.Request'),
        ),
        migrations.AlterField(
            model_name='resturant',
            name='favourite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REZERVAPP.best'),
        ),
    ]
